### ISSUE TITLE
Track Puzzle age / solve time

### ISSUE THREAD

**Issue by akirabaruah** [cardinalitypuzzles/cardboard#219]
Add fields to the Puzzle model to track:

- `created_at` time
- `updated_at` time
- `solved_at` time

**Comment by akirabaruah** [comment]
These field should be user-sortable in the main puzzle table.

**Comment by asdfryan** [comment]
The fields have been added, but the tables are not sortable, right?

**Comment by bcai2** [comment]
Not yet, as of now.

**Comment by bcai2** [comment]
Come to think of it, it would be tricky to make this work in a way that preserves the meta structure that we already have. 

We could sort each "meta forest layer" by time (e.g., earliest to latest created metas, and then earliest to latest of the puzzzles within each meta), or we could just discard the meta tree structure altogether when sorting by time.

**Comment by rgossiaux** [comment]
I agree that sorting by these with the tree structure might be kinda tricky. Not sure what react-table would do by default, if it would sort each level of the tree or sort everything together. 

Maybe we could display them in the puzzle table (or since space is at a premium, maybe just unlock time, or alternatively one single time column that shows unlock time for unsolved puzzles and solve time for solved ones though this could get messy), using relative timestamps (1m ago, 4h ago, etc). I think that'd be pretty useful for solvers (who want to know how old/new various puzzles are).

**Comment by rgossiaux** [comment]
Let's track any UI changes at #459 . Closing this since the model code is there.
