### ISSUE TITLE
Google sheets script still sometimes does not work

### ISSUE THREAD

**Issue by rawxfish** [cardinalitypuzzles/cardboard#372]
![image](https://user-images.githubusercontent.com/1312469/104151949-40b4c080-53ac-11eb-9634-badffb5e3458.png)

**Comment by erwa** [comment]
Could just be us doing too much testing at the moment. Can we pay to increase our API call limit per day?

**Comment by rawxfish** [comment]
That is almost definitely the reason. They seem to be working now. Whenever we make a new sheet, it makes a copy of the custom scripts (see https://script.google.com/). It's not clear to me if/how we can get all the sheets to share one script instead of making copies. I also could not find anything about paying to increase the quota, the only page I found was https://developers.google.com/apps-script/guides/services/quotas. 

Anyways, I don't think this is a critical issue that we have to fix before this weekend, since our sheet creation won't be concentrated on one day during the hunt and it's only an annoyance if the functions stop working.

**Comment by erwa** [comment]
Oh, gotcha, this is only affecting the handy spreadsheet functions that are in our template, but doesn't affect the actual sheets copying and updating done by Small Board. Yeah, it's not a huge issue if the functions stop working during the hunt (though hopefully they don't).

**Comment by rgossiaux** [comment]
How do I actually access the custom script? I opened one of our sheets with the cardinalitypuzzles@ account and clicked "Script editor" but it gives me some generic error.

**Comment by rawxfish** [comment]
It only works for me if cardinalitypuzzles@ is the main or only account I'm logged into. Once I'm on that page, if I add the smallboard GCP project ID under "Project Setting," then I'm able to edit the script using my normal account (probably because I'm added to the GCP project? but I think only RG and I are, so maybe we can test this). This project ID is not carried over when the sheet is copied.

**Comment by rgossiaux** [comment]
One way we could deal with this is by creating a ton of sheets in advance of the hunt and then just renaming them as needed during the hunt, heh.

**Comment by bcai2** [comment]
We could consider just attaching a "master copy" of the custom function script to new blank spreadsheets, rather than making a copy of the script with every spreadsheet. There are ways to do this:

* Via a library: https://developers.google.com/apps-script/guides/libraries#writingLibrary
* Via a webapp: https://developers.google.com/apps-script/guides/content
https://stackoverflow.com/questions/28390885/how-to-run-google-app-script-function-from-another-project

However, either of these will make the custom functions noticeably slower, and we might hit other quotas if we're using the same script for everything. (Also, they'll be a nontrivial amount of work to implement.)

**Comment by fabform** [comment]
Handy to [find google sheet id](https://fabform.io/a/how-to-find-google-sheet-id)

**Comment by rawxfish** [comment]
I believe this issue is fixed with the replacement of scripts with named functions.
