### ISSUE TITLE
Support "custom statuses" or short notes beside a puzzle

### ISSUE THREAD

**Issue by npinsker** [cardinalitypuzzles/cardboard#733]
It's nice to be able to annotate puzzles with short thoughts that go beyond the flexibility of a tag system, e.g. "we're working on this in room 5-201", "we think we're missing a reference", "need 2-3 more people on this"

**Comment by rgossiaux** [comment]
There's a field on the `Puzzle` object that was intended for this: 

https://github.com/cardinalitypuzzles/cardboard/blob/main/puzzles/models.py#L38

It hasn't been implemented yet though. I think so far we haven't missed it much because we use other ways of sharing the information that it would contain. Communications to other people ("we need more people on this puzzle", "can people look at this puzzle, we think we're missing a reference") have just gone through Discord or word of mouth in person, info about the state of the puzzle has gone in the sheet. For where puzzles are being worked on we're using the tag system.

That's not to say we're opposed to the feature afaik, just why we haven't prioritized implementing it yet

**Comment by rawxfish** [comment]
I think we ended up using tags as notes for MH 2024 (e.g. I see tags for "Have to submit group song with 5 people to melody", "don't mark solved puzzles as solved in this round", and "unusual structure"). I don't think it's that difficult to do, so I would vote for having this feature for '25:
